[[main]]
  identifier = "dropdown"
  name = "下拉菜单"
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[main]]
  id = "github"
  parent = "dropdown"
  name = "Github"
  url = "https://github.com/architect-road/architect-road.github.io"
  pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  id = "manual"
  parent = "dropdown"
  name = "用户手册"
  url = "zh-cn/series/manual"
